### ISSUE TITLE
Namespace check method issue

### ISSUE THREAD

**Issue by jmervine** [heroku/configerator#13]
Received reports that checking for set values within a namespace doesn't work as expected when working with override and defaults.

e.g.

```
namespace :foo do
  override :bar, "bar", string
  optional :boo, string
end

# When nothing set, expected...
> foo?
=> false

# Getting...
> foo?
=> true
```

Oddly, looking at the code, I wouldn't expect this to be the case. Need to investigate and test further.

**Comment by jmervine** [comment]
Added [a spec to test for this case](https://github.com/heroku/configerator/commit/24a50f4a675557414cb73787d44b339f6b6ba749). It appears to be working as intended.

**Comment by joshuatobin** [comment]
@jmervine maybe I'm doing something wrong then?

```
  namespace :finalize_incident do
    override :email, "sre@heroku.com", string
    optional :hours, int
  end
```

```
[1] pry(main)> Config.finalize_incident?
=> true
```
